spring:
  application:
    name: pge-mock-services

# Spring Boot embedded server (Actuator management endpoints only)
server:
  port: 7081

# Camel Undertow REST API
rest:
  host: 0.0.0.0
  port: 7080

jwt:
  secret-key: Kraken@2026!ExternalConsumer#JWT_Kong$Secure92xLpZ
  issuer: jwt-issuer
  expiration: 2910000000

external-services:
  rcdc-response:
    url: http://k8s-kong-kongprox-9acef1f816-46ee569626f12d48.elb.ap-south-2.amazonaws.com/rcdcresponse

camel:
  springboot:
    name: PGEMockServicesContext
    stream-caching-enabled: true
  main:
    auto-startup: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,camelroutes
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.pge.mockservices: DEBUG
    org.apache.camel: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
